<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Air-cua-Macbook" ignored="0" name="Register Test - Chrome" tests="1" failures="1" timestamp="2022-08-14T21:14:42 ICT" time="0.828" errors="0">
  <testcase name="registerWithValidAccount" time="0.712" classname="test.TestRegister">
    <failure type="java.lang.AssertionError" message="expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [2]
at test.TestRegister.registerWithValidAccount(TestRegister.java:15)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- registerWithValidAccount -->
</testsuite> <!-- Register Test - Chrome -->
